services:
# ===================================================================================================================
# Catalog
# ===================================================================================================================
  postgres:
    image: postgres:13
    # container_name: postgres-catalog
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: iceberg
      PGDATA: /catalog/pgdata
    volumes:
      - catalog-db-volume:/catalog
    healthcheck:
      test: "pg_isready -U postgres"
      interval: 5s
      retries: 3
    ports:
      - "5433:5432"
    networks:
      - iceberg_net

# ===================================================================================================================
# Trino
# ===================================================================================================================
  trino-coordinator:
    image: 'trinodb/trino:latest'
    # container_name: trino-coordinator
    restart: always
    hostname: trino-coordinator
    ports:
      - '8081:8080'
    volumes:
      - /opt/datalake/trino/coordinator/etc:/etc/trino:ro
    healthcheck:
      test: "curl -f http://localhost:8080/v1/status"
      interval: 15s
      retries: 3
    networks:
      - iceberg_net

  trino-worker:
    image: 'trinodb/trino:latest'
    restart: always
    deploy:
      replicas: 3
    volumes:
      - /opt/datalake/trino/worker/etc:/etc/trino:ro
    healthcheck:
      test: "curl -f http://localhost:8080/v1/status"
      interval: 15s
      retries: 3
    networks:
      - iceberg_net

networks:
  iceberg_net:

volumes:
  catalog-db-volume:
